env:
    - BAZEL_VERSION='0.5.0'
    - BAZEL_VERSION='0.5.1'
    - BAZEL_VERSION='0.5.2'
    - BAZEL_VERSION='0.5.3'
    - BAZEL_VERSION='0.5.4'
    - BAZEL_VERSION='0.6.0'
    - BAZEL_VERSION='0.6.1'
    - BAZEL_VERSION='0.7.0'
    - BAZEL_VERSION='0.10.0'
    - BAZEL_VERSION='0.13.0'
    - BAZEL_VERSION='0.29.1'

sudo: required

before_install:
    - ./before_install.sh

script:
    - bazel build //...
    - bazel test //...
