env:
    - BAZEL_VERSION='0.4.3'
    - BAZEL_VERSION='0.4.4'
    - BAZEL_VERSION='0.4.5'

dist: trusty

sudo: required

before_install:
    - ./before_install.sh

script:
    - ./bazel_build.sh
    - ./bazel_build_and_test.sh
